### ISSUE TITLE
关于登陆

### ISSUE THREAD

**Issue by kylezhang** [doramart/DoraCMS#1]
在登陆时经常会：
1，验证码有错，肯定输入的是正确的，第二次输入就没有问题了；
2，非法数据；我看了代码是validator.isUserName(username) && validator.isPsd(password)中，username总是验证不通过，输入的就是你的文档中的test 000000，dubug到validator.isUserName(username) ，username="test"，然而就是false；

请您看看，谢谢！

**Comment by doramart** [comment]
你好，验证码的问题，我再看一下再回复你。登录密码的问题是正则表达式的问题，已经不支持这种简单密码了，在 [DoraCMS开发文档](http://www.html-js.cn/details/VJpfeMYj.html) 中已经更新了，开发文档以博客中的为准，有时候来不及更新其它地方，抱歉！

**Comment by kylezhang** [comment]
哇，原来您是github online everytime，
恩恩，我看看去；
对了，我breakpoint到了validator.isUserName(username) 这里，我在validator中间件中看不到isUserName方法的源代码，您是怎么弄的？

**Comment by doramart** [comment]
isUserName 是自定义的validator校验扩展，在路由的validat.js文件里，有任何问题或建议可随时联系~~

**Comment by kylezhang** [comment]
1：哦哦，看到了，我之前是直接去了中间件validator中去找的，抱歉！！
//自定义校验扩展
validator.extend('isUserName', function (str) {
    return /^[a-zA-Z][a-zA-Z0-9_]{4,11}$/.test(str);
});

2：用户和用户组的关联是：
admingroups中 "_id"和adminusers中"group" 
对吗？

**Comment by doramart** [comment]
嗯 是的！赞一个 ^_^~

**Comment by kylezhang** [comment]
那在您给的教程中（如下图一）：这个test已经是superadministrator了，为啥操作很多的模块都说没有权限来（如下图二）？
图一：
![user](https://cloud.githubusercontent.com/assets/3679798/10656203/f96fce5a-78ae-11e5-9b64-9eb4aac0820c.png)

图二：
![screenshot from 2015-10-22 11 23 02](https://cloud.githubusercontent.com/assets/3679798/10656227/51a5f770-78af-11e5-9109-ef996950e366.png)

**Comment by doramart** [comment]
你好，你插入的数据应该比较老了，开发文档里的数据是这样的：

···
db.admingroups.insert({
  "_id" : "4yTbsWiI",
  "name" : "超级管理员",
  "power" : "[\"sysTemManage:true\",\"sysTemManage_user:true\",\"sysTemManage_user_add:true\",\"sysTemManage_user_view:true\",\"sysTemManage_user_modify:true\",\"sysTemManage_user_del:true\",\"sysTemManage_uGroup:true\",\"sysTemManage_uGroup_add:true\",\"sysTemManage_uGroup_view:true\",\"sysTemManage_uGroup_modify:true\",\"sysTemManage_uGroup_del:true\",\"sysTemManage_ads:true\",\"sysTemManage_ads_add:true\",\"sysTemManage_ads_view:true\",\"sysTemManage_ads_modify:true\",\"sysTemManage_ads_del:true\",\"sysTemManage_files:true\",\"sysTemManage_files_view:true\",\"sysTemManage_data:true\",\"sysTemManage_data_1:true\",\"sysTemManage_data_1_view:true\",\"sysTemManage_data_1_backup:true\",\"sysTemManage_data_1_del:true\",\"contentManage:true\",\"contentManage_content:true\",\"contentManage_content_add:true\",\"contentManage_content_view:true\",\"contentManage_content_top:true\",\"contentManage_content_modify:true\",\"contentManage_content_del:true\",\"contentManage_cateGory:true\",\"contentManage_cateGory_add:true\",\"contentManage_cateGory_view:true\",\"contentManage_cateGory_modify:true\",\"contentManage_cateGory_del:true\",\"contentManage_tag:true\",\"contentManage_tag_add:true\",\"contentManage_tag_view:true\",\"contentManage_tag_modify:true\",\"contentManage_tag_del:true\",\"contentManage_temp:true\",\"contentManage_temp_add:true\",\"contentManage_temp_view:true\",\"contentManage_temp_modify:true\",\"contentManage_temp_del:true\",\"contentManage_msg:true\",\"contentManage_msg_view:true\",\"contentManage_msg_modify:true\",\"contentManage_msg_del:true\",\"userManage:true\",\"userManage_user:true\",\"userManage_user_view:true\",\"userManage_user_modify:true\",\"userManage_user_del:true\"]",
  "date" : ISODate("2015-06-30T08:04:46.092Z"),
  "__v" : 0
})
···

power 和 password 都有改动
很奇怪，我上传不了截图，你参考下 [DoraCMS开发文档](http://www.html-js.cn/details/VJpfeMYj.html)  
对比数据看看，是有差别的

**Comment by kylezhang** [comment]
OK，
上传不了？是找不到上传的位置呢？（位置在下面：selecting them ）
还是。。。。？

**Comment by doramart** [comment]
刚才看了一下，部分文档没有更新，我再更新一下。上传问题能截图看看报什么错，上传经过了压缩截图处理，需要本地安装GraphicsMagick Display ，否则会上传失败

**Comment by kylezhang** [comment]
嗯，确实部分文档不是最新的O(∩_∩)O~；
现在可以super admin了；
3Q～学习 start。。。。。
恩，我刚才说的说上传不了，是在回答您说的“很奇怪，我上传不了截图，”；

**Comment by doramart** [comment]
呵呵，明白，找到地方了，但是上传出错，可能是网络问题，有问题随时沟通~~

**Comment by kylezhang** [comment]
(⊙v⊙)嗯(⊙v⊙)嗯
那我close了；
