### ISSUE TITLE
使用导入的初始数据无法登录 提示权限不足

### ISSUE THREAD

**Issue by LynanBreeze** [doramart/DoraCMS#102]
https://www.html-js.cn/details/ryn2kSWqZ.html 
按照此教程进行的2.0.5的版本
使用doramart和doracms均无法登录
登录提示权限不足后无法注销，只能等session过期后重新登录。
登录提交后控制台已经输出菜单的项目值，但是页面保持404页面。
道行尚浅不知如何取消解决，请求帮助~

**Comment by doramart** [comment]
数据导入成功了么？能登录进去么(doramart/123456)
