### ISSUE TITLE
关于  cookie-parser middleware  与 express-session

### ISSUE THREAD

**Issue by de1ck** [doramart/DoraCMS#106]
[express-session docs](https://github.com/expressjs/session#api)

这里截取一下原文提示：
**Note** Since version 1.5.0, the [cookie-parser middleware](https://www.npmjs.com/package/cookie-parser) no longer needs to be used for this module to work. This module now directly reads and writes cookies on req/res. Using cookie-parser may result in issues if the secret is not the same between this module and cookie-parser.
[doracms](https://github.com/doramart/DoraCMS/blob/2.0.5/server.js) 相应使用【express-session与cookie-parse】的secret是一致的，但是cookie-parser已经不再需要使用了。

**Comment by doramart** [comment]
好的，谢谢！

**Comment by doramart** [comment]
请升级到 DoraCMS 最新版本
