### ISSUE TITLE
请问pm2部署DoraCMS后内存占用432MB应该不正常吧？

### ISSUE THREAD

**Issue by szy0syz** [doramart/DoraCMS#109]
你好，
我在阿里云服务器中部署了DoraCMSv2.0.5，
服务器为Ubuntu16.04-2核4GB，node为9.4
今天我先 `npm run build` 后 再 `pm2 start server.js --name doracms`内存竟然432MB，
是不是哪里有问题？
![2018-01-20 4 05 27](https://user-images.githubusercontent.com/10555820/35181428-46f89d3a-fdfc-11e7-8a4c-85c962a24ef3.png)

**Comment by szy0syz** [comment]
竟然还彪高~ 😂😂😂
![2018-01-20 4 12 44](https://user-images.githubusercontent.com/10555820/35181453-fad7a06c-fdfc-11e7-9af5-ee868df86091.png)

**Comment by szy0syz** [comment]
我重新弄了下环境，现在290MB内存，请问正常吗？
![2018-01-20 4 31 49](https://user-images.githubusercontent.com/10555820/35181579-85cdaed0-fdff-11e7-81bc-982ce350a677.png)

**Comment by szy0syz** [comment]
好吧，再次配置服务器后正常了！完美~ 
![2018-01-20 7 06 11](https://user-images.githubusercontent.com/10555820/35182728-17a17dd6-fe15-11e7-9d7e-621dce035403.png)
关闭咯~~

**Comment by loaden** [comment]
什么原因？有空分享下经验吗？

**Comment by szy0syz** [comment]
@loaden 
好像是从ubuntu换成centos就正常了~
