### ISSUE TITLE
settings.js修改80端口后报错无法运行,页面显示error500

### ISSUE THREAD

**Issue by JackChius** [doramart/DoraCMS#110]
## 在settings.js修改端口为80后报错无法运行,试了下3000端口和其他几个端口似乎也不行，报错信息如下
**(**标注了几个疑似关注点**)**
` > doracms  | 连接数据成功
**> 0|doracms  | "GET /" 500 - "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"**
> 0|doracms  | "GET /" 500 - "-" "Mozilla/5.0 (Linux; U; Android 6.0.1; zh-CN; NX549J Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/40.0.2214.89 Quark/2.2.1.980 Mobile Safari/537.36"

**> 0|doracms  | server started at localhost:3000**
**> 0|doracms  | 连接数据成功**
> 0|doracms  | "GET /" 500 - "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
> 0|doracms  | "GET /" 500 - "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; rv:11.0) like Gecko"
> 0|doracms  | error during render : /lla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"

> 0|doracms  | { Error: connect ECONNREFUSED 127.0.0.1:8080
> 0|doracms  |     at Object._errnoException (util.js:1022:11)
> 0|doracms  |     at _exceptionWithHostPort (util.js:1044:20)
> 0|doracms  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
> 0|doracms  |   code: 'ECONNREFUSED',
> 0|doracms  |   errno: 'ECONNREFUSED',
> 0|doracms  |   syscall: 'connect',
> 0|doracms  |   address: '127.0.0.1',
> 0|doracms  |   port: 8080,

> 0|doracms  |   config: 
> 0|doracms  |    { adapter: [Function: httpAdapter],
> 0|doracms  |      transformRequest: { '0': [Function: transformRequest] },
> 0|doracms  |      transformResponse: { '0': [Function: transformResponse] },
> 0|doracms  |      timeout: 30000,
> 0|doracms  |      xsrfCookieName: 'XSRF-TOKEN',
> 0|doracms  |      xsrfHeaderName: 'X-XSRF-TOKEN',
> 0|doracms  |      maxContentLength: -1,
> 0|doracms  |      validateStatus: [Function: validateStatus],
> 0|doracms  |      headers: 

> 0|doracms  |       { Accept: 'application/json, text/plain, */*',
> 0|doracms  |         'X-Requested-With': 'XMLHttpRequest',
> 0|doracms  |         'User-Agent': 'axios/0.16.2' },
> 0|doracms  |      method: 'get',
> **0|doracms  |      url: 'http://127.0.0.1:8080/api/ads/getAll',**
> 0|doracms  |      params: { apiSource: 'server' },
> 0|doracms  |      data: undefined },

> 0|doracms  |   request: 
> 0|doracms  |    Writable {
> 0|doracms  |      _writableState: 
> 0|doracms  |       WritableState {
> 0|doracms  |         objectMode: false,
> 0|doracms  |         highWaterMark: 16384,
> 0|doracms  |         finalCalled: false,
> 0|doracms  |         needDrain: false,
> 0|doracms  |         ending: false,
> 0|doracms  |         ended: false,
> 0|doracms  |         finished: false,
> 0|doracms  |         destroyed: false,
> 0|doracms  |         decodeStrings: true,
> 0|doracms  |         defaultEncoding: 'utf8',
> 0|doracms  |         length: 0,
> 0|doracms  |         writing: false,
> 0|doracms  |         corked: 0,
> 0|doracms  |         sync: true,
> 0|doracms  |         bufferProcessing: false,
> 0|doracms  |         onwrite: [Function: bound onwrite],
> 0|doracms  |         writecb: null,
> 0|doracms  |         writelen: 0,
> 0|doracms  |         bufferedRequest: null,
> 0|doracms  |         lastBufferedRequest: null,
> 0|doracms  |         pendingcb: 0,
> 0|doracms  |         prefinished: false,
> 0|doracms  |         errorEmitted: false,
> 0|doracms  |         bufferedRequestCount: 0,
> 0|doracms  |         corkedRequestsFree: [Object] },
> 0|doracms  |      writable: true,
> 0|doracms  |      domain: null,

> 0|doracms  |      _events: 
> 0|doracms  |       { response: [Function: handleResponse],
> 0|doracms  |         error: [Function: handleRequestError] },
> 0|doracms  |      _eventsCount: 2,
> 0|doracms  |      _maxListeners: undefined,
> 0|doracms  |      _options: 
> 0|doracms  |       { maxRedirects: 21,
> 0|doracms  |         protocol: 'http:',
> 0|doracms  |         hostname: '127.0.0.1',
**> 0|doracms  |         port: '8080',**
> 0|doracms  |         path: '/api/ads/getAll?apiSource=server',
> 0|doracms  |         method: 'get',
> 0|doracms  |         headers: [Object],
> 0|doracms  |         agent: undefined,
> 0|doracms  |         auth: undefined,
> 0|doracms  |         pathname: '/api/ads/getAll',
> 0|doracms  |         search: '?apiSource=server' },
> 0|doracms  |      _redirectCount: 0,
> 0|doracms  |      _bufferedWrites: [],
> 0|doracms  |      _onNativeResponse: [Function],
> 0|doracms  |      _currentRequest: 
> 0|doracms  |       ClientRequest {
> 0|doracms  |         domain: null,
> 0|doracms  |         _events: [Object],
> 0|doracms  |         _eventsCount: 5,
> 0|doracms  |         _maxListeners: undefined,
> 0|doracms  |         output: [],
> 0|doracms  |         outputEncodings: [],
> 0|doracms  |         outputCallbacks: [],
> 0|doracms  |         outputSize: 0,
> 0|doracms  |         writable: true,
> 0|doracms  |         _last: true,
> 0|doracms  |         upgrading: false,
> 0|doracms  |         chunkedEncoding: false,
> 0|doracms  |         shouldKeepAlive: false,
> 0|doracms  |         useChunkedEncodingByDefault: false,
> 0|doracms  |         sendDate: false,
> 0|doracms  |         _removedConnection: false,
> 0|doracms  |         _removedContLen: false,
> 0|doracms  |         _removedTE: false,
> 0|doracms  |         _contentLength: 0,
> 0|doracms  |         _hasBody: true,
> 0|doracms  |         _trailer: '',
> 0|doracms  |         finished: true,
> 0|doracms  |         _headerSent: true,
> 0|doracms  |         socket: [Object],
> 0|doracms  |         connection: [Object],

**> 0|doracms  |         _header: 'GET /api/ads/getAll?apiSource=server HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nX-Requested-With: XMLHttpRequest\r\nUser-Agent: axios/0.16.2\r\nHost: 127.0.0.1:8080\r\nConnection: close\r\n\r\n',**
> 0|doracms  |         _onPendingData: [Function: noopPendingOutput],
> 0|doracms  |         agent: [Object],
> 0|doracms  |         socketPath: undefined,
> 0|doracms  |         timeout: undefined,
> 0|doracms  |         method: 'GET',
> 0|doracms  |         path: '/api/ads/getAll?apiSource=server',
> 0|doracms  |         _ended: false,
> 0|doracms  |         res: null,
> 0|doracms  |         aborted: undefined,
> 0|doracms  |         timeoutCb: null,
> 0|doracms  |         upgradeOrConnect: false,
> 0|doracms  |         parser: null,
> 0|doracms  |         maxHeadersCount: null,
> 0|doracms  |         _redirectable: [Circular],
> 0|doracms  |         [Symbol(outHeadersKey)]: [Object] },
**> 0|doracms  |      _currentUrl: 'http://127.0.0.1:8080/api/ads/getAll?apiSource=server' },**
> 0|doracms  |   response: undefined }
**> 0|doracms  | (node:21249) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 31): Error: connect ECONNREFUSED 127.0.0.1:8080**

0|doracms  | "GET /" 500 - "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
`

**Comment by doramart** [comment]
你这是哪个版本的代码啊

**Comment by JackChius** [comment]
@doramart   2.0.5的版本

**Comment by doramart** [comment]
我感觉你的端口号没改过来，你搜一下你代码里哪里还有 8080

**Comment by aizaimenghuangu** [comment]
修改完端口后，需要重新npm run build，否则不会生效，且会提示500.

**Comment by doramart** [comment]
是的，需要重新 build
