### ISSUE TITLE
log4js initPath 

### ISSUE THREAD

**Issue by de1ck** [doramart/DoraCMS#113]
[logUtil](https://github.com/doramart/DoraCMS/blob/2.0.5/utils/logUtil.js) 
log4js 在2.0+ 版本中appenders 是对象而不是数组 可以使用
**ES2017 引入了跟Object.keys配套的Object.values和Object.entries，作为遍历一个对象的补充手段，供for...of循环使用。**

 const { keys, values, entries } = Object;
      for (const [key, value] of entries(configure.appenders)) {
        confirmPath(baseLogPath + value.path);
      }

**Comment by doramart** [comment]
请升级到 DoraCMS 最新版本
