### ISSUE TITLE
Error in render: "TypeError: Cannot read property 'userName' of undefined"

### ISSUE THREAD

**Issue by aizaimenghuangu** [doramart/DoraCMS#114]
后台添加文章来源选择用户发布会导致文章列表不可见
操作步骤：
1、后台添加文章；
2、来源选择【用户发布】
结果：
1、文章列表会不可见，会提示：Error in render: "TypeError: Cannot read property 'userName' of undefined"

**Comment by doramart** [comment]
请升级到 DoraCMS 最新版本
