### ISSUE TITLE
还是mongodb用户鉴权问题

### ISSUE THREAD

**Issue by xxgtimk** [doramart/DoraCMS#116]
npm run dev 起不来
日志：
server started at localhost:8080
连接数据成功
Unhandled rejection MongoError: not authorized on doracms2 to execute command { listIndexes: "sessions", cursor: {} }
    at Function.MongoError.create (/Users/wanglongbo/Desktop/work/DoraCMS/node_modules/mongodb-core/lib/error.js:31:11)

(node:1344) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: not authorized on doracms2 to execute command { listIndexes: "usernotifies", cursor: {} }
(node:1344) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
babel-preset-env: `DEBUG` option

请问楼主如何解决，之前也有人提出这个问题，但我不知怎么解决

**Comment by xiongleio** [comment]
开发用无密码模式。
#auth=true
