### ISSUE TITLE
[vue-router] Duplicate named routes definition

### ISSUE THREAD

**Issue by aizaimenghuangu** [doramart/DoraCMS#122]
访问首页会有如下提示：
[vue-router] Duplicate named routes definition: { name: "index", path: "/page/:current(\d+)?" }
[vue-router] Duplicate named routes definition: { name: "category", path: "/:cate0/:cate1?___:typeId?/:current(\d+)?" }

这个是什么原因导致？

**Comment by doramart** [comment]
请升级到 DoraCMS 最新版本
