### ISSUE TITLE
相关功能改进

### ISSUE THREAD

**Issue by epubreader** [doramart/DoraCMS#126]
相关功能改进：
1. tag 设置为不是必选的
2. 增加文字的最大字数， 字数一多会提示保存不成功
3. 前台和后台功能分开， 后台功能可以用另外一个端口， 在一起打包会不会太大了

继续体验中

**Comment by doramart** [comment]
谢谢，后续考虑优化

**Comment by doramart** [comment]
DoraCMS 2.1.4 把前后台拆分了，敬请关注
