### ISSUE TITLE
checkSystemInfo

### ISSUE THREAD

**Issue by moyuanhua** [doramart/DoraCMS#127]
![tim 20180309130735](https://user-images.githubusercontent.com/7417755/37191471-d95f388c-239a-11e8-9216-2146eb8a5ad5.png)
这一段代码的功能是什么
位于 server/controller/adminUser.js
为何我在路由中没有找到'/system/checkSystemInfo

**Comment by doramart** [comment]
这个接口暂时用不上，功能主要是记录下当前已经上线的使用doracms系统的站点，可以忽略，也可以注释
