### ISSUE TITLE
doracms 2.0.5 遇到的问题，文档管理加载不出来数据

### ISSUE THREAD

**Issue by huangdeyao** [doramart/DoraCMS#128]
Error in render: "TypeError: Cannot read property 'userName' of undefined"
found in
---> <ElTableBody>
       <ElTable>
         <DataTable> at D:\vue\DoraCMS-2.0.5\src\manage\components\content\dataTable.vue
           <ElCol>
             <ElRow>
               <Index> at D:\vue\DoraCMS-2.0.5\src\manage\components\content\index.vue
                 <ElCol>... (1 recursive calls)
                   <ElRow>
                     <Home> at D:\vue\DoraCMS-2.0.5\src\manage\components\Home.vue
                       <Root>

还想知道在哪里修改发布文章可以直接发布，不需要审核；谢谢

**Comment by doramart** [comment]
你是否按照教程导入了基础数据？https://www.html-js.cn/details/ryn2kSWqZ.html

**Comment by huangdeyao** [comment]
数据导入是成功的，开始的时候还是可以发表文章，后面就突然不行了

**Comment by doramart** [comment]
你是不是改了什么代码导致的，另外直接发布可以设置文章的state属性为ture就可以

**Comment by huangdeyao** [comment]
没有呢，才入坑vue代码不是很懂；我清理一下数据数据库重新导入数据后还是有一些问题：
1、导入表报：no indexes to restore；但是登录用户信息导入成功，功能正常
2、用超级管理员发布文章，不成功；后台报错： UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 41): TypeError: Cannot read property '_id' of undefined；新创建超级管理员登录后发布成功。
3、state属性 在哪个代码文件里面添加

谢谢

**Comment by doramart** [comment]
忘记了，好像在api.js吧

**Comment by huangdeyao** [comment]
恩，好的；我找到位置了，我在server/routers/api.js  @修改；我尝试在这UserAddContent.vue中设置state为true，可惜没成功；不知道在哪里设置，也不知道怎么设置 =，=！，非常感谢
// 查询文档列表
// router.get('/content/getList', (req, res, next) => { req.query.state = true; next() }, Content.getContents);
router.get('/content/getList', (req, res, next) => { next() }, Content.getContents);
// 查询简单的文档列表
// router.get('/content/getSimpleListByParams', (req, res, next) => { req.query.state = true; next() }, Content.getContents)
router.get('/content/getSimpleListByParams', (req, res, next) => { next() }, Content.getContents)

**Comment by aizaimenghuangu** [comment]
Error in render: "TypeError: Cannot read property 'userName' of undefined" 

以上问题的原因是：前端注册了用户，但是后台没有导致。

**Comment by whpersonal** [comment]
你好，请问超级管理员账号是需要自己在数据库中添加的吗?doracms/123456只是测试账号，没有修改权限。

**Comment by doramart** [comment]
doramart/123456

**Comment by terenceyhj** [comment]
DoraCMS在没有初始化数据的情况下可以启动？

**Comment by terenceyhj** [comment]
DoraCMS2.x在没有初始化数据的情况下可以启动？可以用 npm run init
