### ISSUE TITLE
启动项目时报错Syntax Error: Unexpected token

### ISSUE THREAD

**Issue by ZhangPingFan** [doramart/DoraCMS#130]
运行环境：mac／node v8.9.3
npm run dev 后报错如图，尝试如下修改webpack.base.config.js，但貌似只解决了一部分，求助。
rules: [{
            test: /\.js$/,
            loader: 'babel-loader',
            exclude: /node_modules/,
            query:{
                babelrc: false,
                presets: [
                    'es2015',
                    'stage-3'
                ]
            }
        }, {
            test: /\.json$/,
            loader: 'json-loader'
        }]

<img width="621" alt="2018-03-28 11 01 57" src="https://user-images.githubusercontent.com/34783075/38038467-95e3294a-32dd-11e8-8611-865b59fd18f4.png">

**Comment by doramart** [comment]
请升级到 DoraCMS 最新版本
