### ISSUE TITLE
用户名或密码错误

### ISSUE THREAD

**Issue by ghost** [doramart/DoraCMS#132]
![image](https://user-images.githubusercontent.com/19482459/38224898-b677bac2-3724-11e8-98b0-51ec175401e6.png)

After installed on my local, I tried to access via `doracms`/`123456`, but it says `用户名或密码错误`.

**Comment by ghost** [comment]
Forgot to init it first.

**Comment by zjdgx** [comment]
@xdrone2008 How to init?
