### ISSUE TITLE
为什么配置了广告页和公告，首页并没有显示？

### ISSUE THREAD

**Issue by pkuhonker** [doramart/DoraCMS#133]
在后台系统管理界面配置了，也勾选显示选项了，但是首页没有任何显示，日志也没有任何报错。重启服务器也无法解决。

**Comment by Bob-huang-gdut** [comment]
在后台系统管理界面配置了，也勾选显示选项了，但是首页没有任何显示，日志也没有任何报错。重启服务器也无法解决。

**Comment by doramart** [comment]
公告是显示在注册用户中心的 ，广告页需要在代码中配置广告id
