### ISSUE TITLE
Mac 环境下执行 npm run build 报错

### ISSUE THREAD

**Issue by Sean-Wang** [doramart/DoraCMS#135]
按照 DoraCMS2.0 linux部署(生产环境)教程内容进行操作。已经把 DoraCMS 代码 Clone 到本地，并且成功执行了 `npm install`，再接下来执行 `npm run build` 命令的时候报错：

![image](https://user-images.githubusercontent.com/1193073/38541075-8878c5ec-3cd0-11e8-86ec-f6d495833967.png)

请问应该如何解决这个问题，谢谢。

**Comment by Sean-Wang** [comment]
问题已解决，谢谢开源了这么好的CMS系统。

**Comment by doramart** [comment]
感谢关注 希望能帮到你！
