### ISSUE TITLE
npm install 依赖安装失败

### ISSUE THREAD

**Issue by ghost** [doramart/DoraCMS#137]
![image](https://user-images.githubusercontent.com/27983686/39344223-c13ac7d6-4a13-11e8-8cce-469a39de1a7c.png)

**Comment by SummerF** [comment]
我也遇到类似的情况，node版本换成8试一下

**Comment by guiyuan** [comment]
怎么解决的？

**Comment by loaden** [comment]
node版本只能用8或者9
npm可能要换成cnpm，或者翻墙。

**Comment by doramart** [comment]
可选用 cnpm install
