### ISSUE TITLE
关于部署到服务器

### ISSUE THREAD

**Issue by 997882717** [doramart/DoraCMS#139]
你好，首先感谢这位开发者的无私奉献，我遇到了一个问题。
我部署到服务器后看到文件里有一个http://域名/__webpack_hmr，也就是这个应该不是线上的，我不知道怎么样才能在window上搭建一个非开发模式的服务
搭建好环境后我有如下操作：1 npm install 2 npm run dev 3 npm run build 4 npm run start  然后我在dist看到了生产出来的东西，但是这个要怎么运行呢？我把他里面的东西单独拿出来是不能运行的。而直接npm start则会建立一个开发模式的服务

**Comment by doramart** [comment]
第四步 node server.js 或者 pm2 start server.js  前提是数据库要正常启动且配置密码正确

**Comment by doramart** [comment]
我看到你在segmentfault 上的提问了，那种情况是因为服务器环境变量不正确，需要配置成 production

**Comment by 997882717** [comment]
谢谢

**Comment by loaden** [comment]
解决了就close吧
