### ISSUE TITLE
v-model绑定state为什么没有报Do not mutate vuex store state outside mutation handlers

### ISSUE THREAD

**Issue by lastSeries** [doramart/DoraCMS#143]
vue文件中许多form表单的属性值全都放在vuex中state里，在computed中通过this.$store.getters.XXX获取表单的属性值，并通过v-model进行数据双向绑定，那么用户修改表单中数据后，不就会触发并修改state中的值了，并且报Do not mutate vuex store state outside mutation handlers，为什么大佬你的代码并没有更新state中的值，报这个错误呢，烦请大佬调拨一番，小白在此谢过了

**Comment by doramart** [comment]
请移步 vue 官方文档，谢谢！
