### ISSUE TITLE
请问后台管理登录时效这个功能怎么关闭

### ISSUE THREAD

**Issue by ghost** [doramart/DoraCMS#144]
首先很感谢作者提供的CMS
我在二次开发过程中发现后台管理登录后过一段时间就需要重新登录，因为我需要在后台管理里面添加文章，需要操作很长时间，重复登录很麻烦，想请问能不能关闭这个功能，或者延长登录的时间。我查看代码没能解决这个问题(我是新手...)
如果可以实现的话，烦请告知。

**Comment by doramart** [comment]
参考这里：  [session时间设置](https://github.com/doramart/DoraCMS/issues/98)
