### ISSUE TITLE
基础数据已导入      但是 账号:doracms  密码:123456报错   请帮忙解决一下  感谢！

### ISSUE THREAD

**Issue by niuyasen123** [doramart/DoraCMS#146]
![default](https://user-images.githubusercontent.com/24853463/40966435-0c2efba2-68e3-11e8-8fdb-0aae3fb30462.png)

**Comment by niuyasen123** [comment]
![default](https://user-images.githubusercontent.com/24853463/40966877-3fc1be68-68e4-11e8-9c51-591e725d365a.png)

**Comment by doramart** [comment]
麻烦更新最新的版本(2.1)后重试

**Comment by yanghcc** [comment]
遇到同样的问题。
![image](https://user-images.githubusercontent.com/17024693/41458329-dfc121a2-70b8-11e8-91e3-63c0c7eb2501.png)

**Comment by doramart** [comment]
使用 doramart/ 123456 试试

**Comment by niuyasen123** [comment]
更新到最新版本 2.1  问题已解决

**Comment by lovemybb** [comment]
基础数据在哪里啊

**Comment by loaden** [comment]
@lovemybb 看下README部署相关文章。
建议close
