### ISSUE TITLE
发布文章排版失效

### ISSUE THREAD

**Issue by LiuChangkang** [doramart/DoraCMS#147]
发布文章的时候文章的排版失效，再更新一次文章后排版正常。

**Comment by doramart** [comment]
排版失效能截图看看嘛？

**Comment by LiuChangkang** [comment]
![bug1](https://user-images.githubusercontent.com/28344910/41073463-03d1c648-6a36-11e8-9f20-e276e81f24bc.png)
![bug2](https://user-images.githubusercontent.com/28344910/41073466-08e33522-6a36-11e8-9436-0ce770a1647f.png)
![bug3](https://user-images.githubusercontent.com/28344910/41073470-0bcb2f10-6a36-11e8-98e0-b0cd330055a1.png)
![bug4](https://user-images.githubusercontent.com/28344910/41073473-0ff2e998-6a36-11e8-9722-e9f9fa8a09ed.png)
![bug5](https://user-images.githubusercontent.com/28344910/41073474-137bb752-6a36-11e8-8c1e-bf5c603bd41b.png)

**Comment by doramart** [comment]
请使用 doracms 2.1.3
