### ISSUE TITLE
为什么需要redis

### ISSUE THREAD

**Issue by daydaystar** [doramart/DoraCMS#148]
没装redis
npm start 一直报错，是必须要装吗

**Comment by niuyasen123** [comment]
![image](https://user-images.githubusercontent.com/24853463/41208805-58acd858-6d59-11e8-94ab-9a2be33e40b6.png)

**Comment by niuyasen123** [comment]
最新版本2.1.0是需要的  我下载了redis 但是还没设置密码(不影响启动项目)     
![image](https://user-images.githubusercontent.com/24853463/41208849-9e5c796c-6d59-11e8-9741-f4e4ab97be47.png)

**Comment by doramart** [comment]
本地redis需要配置密码

**Comment by niuyasen123** [comment]
哦哦  好的  谢谢提醒

**Comment by daydaystar** [comment]
![image](https://user-images.githubusercontent.com/23712342/41209673-8cf58a64-6d5f-11e8-8c24-4c0a1ed0f196.png)
我关了这个还是报错呀

**Comment by doramart** [comment]
redis需要打开 设置为true

**Comment by daydaystar** [comment]
我知道了  谢谢解答

**Comment by biluochun** [comment]
为什么不只依赖mongodb
