### ISSUE TITLE
调试方案

### ISSUE THREAD

**Issue by guoweibo** [doramart/DoraCMS#155]
您好，我用webstorm点dev模式，每次修改代码重启都要15s，我想问下有更好的解决方案吗？谢谢了

**Comment by wennjie** [comment]
把 vue渲染 那里的参数单独拿出来写， 时间长是因为vue模板编译的原因。

**Comment by wennjie** [comment]
@guoweibo 把 vue渲染 那里的参数单独拿出来写， 时间长是因为vue模板编译的原因。

**Comment by guoweibo** [comment]
@wennjie 是在server.js吗？刚入手也不太熟悉，谢谢大牛了

**Comment by wennjie** [comment]
@guoweibo  
1.server.js 里面 找到`
// 由 html-webpack-plugin 生成
let backend
// 创建来自 webpack 生成的服务端包
let renderer
if (vueDev) { //原本是 isProd 更改成自己的变量控制
    require('./build/setup-dev-server')(app, (_template) => {
        backend = _template.backend
    })
}`
2.找到`app.get('/manage', authSession, function (req, res) {
    AdminResource.getAllResource(req, res).then((manageCates) => {
        let adminPower = req.session.adminPower;
        let currentCates = JSON.stringify(siteFunc.renderNoPowerMenus(manageCates, adminPower));
        if (!vueDev) {/原本是 isProd 更改成自己的变量控制
...`
3. 原理：作者逻辑，是不是开发模式，如果是开发模式，那么代码走的是第一步，否则走的是第二步。如果是开发后端service 的代码 那么，vue 后台管理部分的服务逻辑 渲染时间过于长。 那就直接先 yarn/ npm  build 之后 我们得到了 dist 代码。  server.js 里面我们不走第一步，只走第二步。 就很快 就可以执行程序

**Comment by guoweibo** [comment]
多谢热心大牛了，帮了很大忙

**Comment by doramart** [comment]
请升级到 DoraCMS 最新版本
