### ISSUE TITLE
这个需要怎么配，而且redis的开放不起作用，即便是设置成false 程序还是进行连接

### ISSUE THREAD

**Issue by denlly** [doramart/DoraCMS#156]
3|server   | node_redis: Warning: Redis server does not require a password, but a password was supplied.
3|server   | node_redis: Warning: Redis server does not require a password, but a password was supplied.
3|server   | Error in MongoDb connection: MongoError: Authentication failed.

怎么修改

**Comment by denlly** [comment]
纠正一下“而且redis的关闭配置不起作用”

**Comment by doramart** [comment]
开发和测试环境都配 true吧

**Comment by wangjue666** [comment]
我也遇到同样问题了,有什么解决办法吗、

**Comment by wangjue666** [comment]
很好,这鬼玩意让我学会用redis了，真香！

**Comment by doramart** [comment]
目前的版本需要安装redis
