### ISSUE TITLE
npm i  ERROR

### ISSUE THREAD

**Issue by lingchendeye** [doramart/DoraCMS#157]
Unexpected end of JSON input while parsing near '..."version":"0.2.0","de'
![image](https://user-images.githubusercontent.com/12905351/44097346-1e305b34-a010-11e8-9f44-9daed867585a.png)
error log
![image](https://user-images.githubusercontent.com/12905351/44097635-d0ebf292-a010-11e8-8878-1f596e800e36.png)
node v10.8.0
npm v6.2.0

**Comment by doramart** [comment]
这个可以忽略吧，能跑起来吗？
