### ISSUE TITLE
adsId 为什么写死在模板里

### ISSUE THREAD

**Issue by lovemybb** [doramart/DoraCMS#160]
![image](https://user-images.githubusercontent.com/5569015/45204716-af505380-b2b2-11e8-8f20-476d0a13e567.png)
adsId 为什么写死在模板里

**Comment by lovemybb** [comment]
模板编辑，在分布式部署上有问题吗。编辑完怎么同步所有的服务器啊

**Comment by loaden** [comment]
考虑下二次开发并贡献代码

**Comment by doramart** [comment]
你可以通过编辑模板来修改id
