### ISSUE TITLE
npm run build(无错) 之后 dist 目录无法运行 Unexpected token { in JSON at position 1

### ISSUE THREAD

**Issue by ryan1000** [doramart/DoraCMS#161]
在npm run build 成功之后，把dist目录 上传到服务器 能正常访问，但没有任何内容 firebug查看 报js错误  Unexpected token { in JSON at position 1

**Comment by doramart** [comment]
项目运行仅靠dist是不行的，整个项目其他目录都要在，参考我博客的教程[DoraCMS2.0 linux部署(生产环境)教程](https://www.html-js.cn/details/ry4-B-hkf.html)

**Comment by ryan1000** [comment]
服务器上我运行 pm2 npm start 之后dist被清空，我是不是要把dist单独 拿出来建站点？ 如果单独拿出来了，dist运行一个端口，doracms程序 运行一个端口，dist那边的就拿不到数据了。

**Comment by doramart** [comment]
这是启动命令： `pm2 start server.js --name doracms` ，  pm2 npm start 是什么东东？

**Comment by ryan1000** [comment]
哦，我写错了。 我pm2 start server.js --name doracms启动项目之后，dist被清空了。NODE_ENV设置了 production。项目运行起来后，没有用到dist目录 。如何单独把dist目录拿出来建站点dist目录 又拿不到数。这个应该怎样操作。谢

**Comment by doramart** [comment]
dist目录是有用的，不能挪位置， `pm2 start server.js --name doracms` 这个脚本是不会做清空操作的，你需要确认下你是否改了package.json 等文件

**Comment by ryan1000** [comment]
好的，谢谢。

**Comment by ryan1000** [comment]
问题已经解决，谢谢两位的热心回答。问题出在package.json的 scripts中的start命令["start": "npm run static&& cross-env NODE_ENV=production MICRO_CACHE=true node ./server",] 这里面的npm run static就会清空dist但又没有重新生成。把这句去掉或是改为npm run build就可以了。有点奇怪“doramart/DoraCMS”为什么没有问题？
