### ISSUE TITLE
大佬！ 为什么我执行 npm run build 后 执行 node server, webpack服务也在启动呢？

### ISSUE THREAD

**Issue by wangjue666** [doramart/DoraCMS#169]
用 pm2启动  项目内存一度飙升到800多M，好吓人，是我哪一步执行出问题了吗？

**Comment by doramart** [comment]
生产管理需要配置环境变量

**Comment by wangjue666** [comment]
恩恩 多谢大神指正，还有一个问题大神。。 我用的是2.1 版本的， 可是根目录下没有 etc目录的。。  我搜索了下 node_modules下面有个，但是没有profile这个文件 搜profile这个文件 文件里面也没有环境变量这个配置项， issues 里面也木有这个傻缺问题, 我该在哪里操作呢。。？大神

**Comment by doramart** [comment]
etc是哪里提示的？

**Comment by loaden** [comment]
etc目录不应该是/根目录下吗？与DoraCMS没有关系。配置生产环境变量，执行build，启用redis密码，应该就可以完成部署了吧。

**Comment by wangjue666** [comment]
政府给提供的windows服务器，，， 神tm难用
