### ISSUE TITLE
npm run dev 跑不起来

### ISSUE THREAD

**Issue by zenonux** [doramart/DoraCMS#170]
![image](https://user-images.githubusercontent.com/8474239/47960423-bedfe480-e036-11e8-81da-6d10129f6eb7.png)
开发环境：
系统 ：macos 
node： 11.1.1
mongodb: 4.0.3

数据库文件已导入，启动端口已改为8585

**Comment by doramart** [comment]
还不支持node 10，目前兼容的是8以内的版本

**Comment by zenonux** [comment]
> 还不支持node 10，目前兼容的是8以内的版本

后来发现了，用8.1.0 就可以了，建议文档上说明一下还要安装redis，以及默认管理员账号密码等。
