### ISSUE TITLE
mac无法进入dr-admin后台系统，前端可以正常显示

### ISSUE THREAD

**Issue by wshenglong** [doramart/DoraCMS#174]
(node:40129) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at AdminResource.getAllResource.then (/Users/jsonshenglong/Wdocumont/web_project/DoraCMS/DoraCMS/server.js:216:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:40129) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:40129) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by doramart** [comment]
导入基础数据了吗

**Comment by wshenglong** [comment]
按照教程导入了

**Comment by sandfilter** [comment]
出现同样问题，在登录后台时出现报错，已确认导入基础数据

**Comment by doramart** [comment]
请升级到 DoraCMS 最新版本
