### ISSUE TITLE
config.useHttpsDomain配置目前是否可支持使用https域名？

### ISSUE THREAD

**Issue by chanlily** [doramart/DoraCMS#175]
config.useHttpsDomain配置true的时候，会报错
请问当前版本可以支持https域名吗？若不支持，哪些地方是需要配置的？
在文件上传的地方，一直不能成功，找不到原因，总是POST-502

**Comment by doramart** [comment]
程序跟https没有关系

**Comment by chanlily** [comment]
问题已解决，谢谢
