### ISSUE TITLE
请问下大家安装的环境

### ISSUE THREAD

**Issue by govue** [doramart/DoraCMS#177]
一直没有安装成功，网站搜了下说是node版本过高，但通过nvm切换到8.1.0也还是一样的报错，就问下大家没有安装成功的，都是在什么环境下安装成功的。

**Comment by hxrealm** [comment]
我这边安装还是很顺利的，唯一出现问题主要是Mongodb数据导入总是失败，已经解决了，现在主要是发布CMS本身问题比较多！

**Comment by govue** [comment]
终于在本地测试成功了，|从github上clone的代码怎么都跑不出来，从gitee上的代码可以跑通。另外本地还需要安装redis，在配置文件中把redis改为False也提示报redis错误。如果mogodb使用的不是本地的话，还需要修改server\lib\models\index.js中《mongoose.connect("mongodb://127.0.0.1/" + settings.DB, { useMongoClient: true });》处的IP，改为你实际的数据库IP，最后就是数据导入，只需要导入.bosn文件。希望大家不要踩我踩过的坑，玩了整整两天才跑出来，最后在放弃的关键时刻还是坚持了下来。

**Comment by doramart** [comment]
是需要耐心！

**Comment by govue** [comment]
> 我这边安装还是很顺利的，唯一出现问题主要是Mongodb数据导入总是失败，已经解决了，现在主要是发布CMS本身问题比较多！

不知道你试过mongodb开启认证模式后还能不能正常打开页面？

**Comment by soakit** [comment]
部署的2.1.1，成功了。
参照这个，https://www.html-js.cn/details/ryn2kSWqZ.html
另外注意的是，要安装并启动**redis**
