### ISSUE TITLE
我本地可以安装 在服务器上安装出现这个错误，谁解释下

### ISSUE THREAD

**Issue by NiceSmall** [doramart/DoraCMS#178]
![qq 20181122143413](https://user-images.githubusercontent.com/6635583/48885603-d48d4080-ee63-11e8-9996-437d66a2c337.png)

**Comment by NiceSmall** [comment]
![qq 20181122143707](https://user-images.githubusercontent.com/6635583/48885684-259d3480-ee64-11e8-88ae-1f6b6a534ad4.png)

**Comment by doramart** [comment]
用cnpm吧

**Comment by NiceSmall** [comment]
code EINTEGRITY
package-lock.json文件，删掉
重新npm i 就可以了
