### ISSUE TITLE
mongodb权限问题

### ISSUE THREAD

**Issue by govue** [doramart/DoraCMS#179]
mongodb设置权限验证后报如下错误：

data: {}
message: "获取  失败: not authorized on doracms2 to execute command { find: &quot;contentcategories&quot;, filter: { enable: true }, projection: { id: 1 }, $db: &quot;doracms2&quot; } "
server_time: 1542871444379
status: 500

数据库用户权限试过dbOwner和dbAdmin都不行，但数据库用户能正常连接数据库也能读写数据，不知道问题出在哪儿？
不可能数据库关掉权限验证来跑网站吧

**Comment by doramart** [comment]
https://www.html-js.cn/details/ry4-B-hkf.html
