### ISSUE TITLE
编辑模板的时候提示no power请问要怎么解决

### ISSUE THREAD

**Issue by wujianrong** [doramart/DoraCMS#182]
![image](https://user-images.githubusercontent.com/19931872/49130720-4a842280-f310-11e8-8091-353ca852c2cb.png)

**Comment by changgeee** [comment]
post拿不到请求体的问题
https://github.com/doramart/DoraCMS/issues/181

**Comment by qiaojianfeng** [comment]
const form = new formidable.IncomingForm();
使用项目中的这个方法接受post请求，或者直接改成get请求

**Comment by doramart** [comment]
问题已解决，请下载最新版本(v2.1.2)
