### ISSUE TITLE
访问详情页时有时会报错Error: template not found

### ISSUE THREAD

**Issue by irradiate** [doramart/DoraCMS#185]
不是每次都出现， 同一个页面刷新几次就会出现， 
Error: template not found: /opt/web-cms-develop/views/dorawhite/undefined.html

在测试环境没有这个问题

**Comment by doramart** [comment]
是不是没有编译

**Comment by jzYuchn** [comment]
您好，请问解决了吗？我现在后台登陆进去显示server error，看服务器日志报的就是这个错，template not found:/

**Comment by jzYuchn** [comment]
@doramart

**Comment by doramart** [comment]
您没有导入基础数据，谢谢！
