### ISSUE TITLE
 还是Mongodb 权限问题

### ISSUE THREAD

**Issue by qiaojianfeng** [doramart/DoraCMS#189]
Linux环境 ，mongodb :v4.0.6 
/usr/local/mongodb/ 这个地方auth校验通过，正常启动mongo
通过servicejs启动报MongoError: command insert requires authentication 
无奈Linux小白，实在找到不到问题根源

**Comment by qiaojianfeng** [comment]
问题已经解决是权限问题，搞了一天脑子秀逗了😄

**Comment by doramart** [comment]
嗯嗯 解决就行
