### ISSUE TITLE
一些看法建议

### ISSUE THREAD

**Issue by goldcome** [doramart/DoraCMS#19]
先感谢@doramart 把这个cms开源供大家使用，很好的一个项目，但应该有很多需要改善的，刚刚装了试了下，就说下我个人看法
1. 为啥添加用户一定要全部信息都齐全？
2. 添加文章也是有这个要求,其他不说，一定要有缩略图才行，有点疼...
3. 后台查看文章列表只能看，建议在标题做个链接，可以直接点击预览
4. 不知道为啥，我添加了一篇文章，后面去后台编辑的时候发现内容是空的，但前台显示却是有内容
5. 姓名为什么一定要强制中文，这个有点不解
6. 缩略图不能选择已经上传过图片的，只能重新传，可以选择就灵活

**Comment by doramart** [comment]
你好，建议很好。
1、关于信息齐全的问题，其实也可以不用完全，可以在源代码里把 表单的require属性去掉就可以了，图片缩略图也是一样，这个我后面优化一下，可以只填入基本信息就可以提交
2、关于后台查看文章列表，应该是可以点击链接的，但是一级分类下的文章没加链接
3、添加文章，后台编辑是空白的问题，你刷新一下页面就好了，这个是angularjs绑定的ueditor，但是总有点问题。这个是遗留问题，我尽量在后面的版本优化这个问题。
4、姓名问题，当时的设计是“为中国用户打造”，没想那么多，用户名是可以英文的，这个你可以根据自己的需要修改一下。
5、缩略图问题，确实也存在，这里需要一个文件管理器选择，建议很好，后面的开发中考虑进去。
非常感谢您的建议！
