### ISSUE TITLE
请问这个 typechecker 是什么？

### ISSUE THREAD

**Issue by ZhangWren** [doramart/DoraCMS#191]
![image](https://user-images.githubusercontent.com/25240164/53322619-e248db00-3916-11e9-92b2-257b3c0c47c6.png)
总是报这错误

node：8.15.0
环境：windows 10

尝试过的方法：删除 package-lock.json，issues查询，全局搜索 typechecker

**Comment by doramart** [comment]
跟这个没关系，使用cnpm试试，或者翻墙

**Comment by ZhangWren** [comment]
@doramart 已经出去了，从来没用过cnpm，不知道咋回事了。。。。
