### ISSUE TITLE
adsId怎么设置或者怎么找到呢？

### ISSUE THREAD

**Issue by Macjoly** [doramart/DoraCMS#192]

**Comment by Macjoly** [comment]
![1](https://user-images.githubusercontent.com/15778223/53622756-dd956700-3c35-11e9-9907-9a2cb9efa020.png)

**Comment by Macjoly** [comment]
已经解决了，直接在广告管理里面取就行了，然后把模板改成相应的id就行了

**Comment by doramart** [comment]
厉害！

**Comment by loaden** [comment]
呵呵，可以close了
