### ISSUE TITLE
在centos 上尝试部署一直报Invalid or unexpected token：system_noPower: '对不起，您无权执行该操作

### ISSUE THREAD

**Issue by rainyulei** [doramart/DoraCMS#194]
`M2      | App [ff:0] exited with code [1] via signal [SIGINT]
PM2      | App [ff:0] starting in -fork mode-
PM2      | App [ff:0] online
0|ff     | /home/new-land/configs/settings.js:54
0|ff     |     system_noPower: '对不起，您无权执行该操作�?,
0|ff     |                     ^^^^^^^^^^^^^^^^
0|ff     | SyntaxError: Invalid or unexpected token
0|ff     |     at new Script (vm.js:80:7)
0|ff     |     at createScript (vm.js:274:10)
0|ff     |     at Object.runInThisContext (vm.js:326:10)
0|ff     |     at Module._compile (internal/modules/cjs/loader.js:664:28)
0|ff     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
0|ff     |     at Module.load (internal/modules/cjs/loader.js:600:32)
0|ff     |     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
0|ff     |     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
0|ff     |     at Module.require (internal/modules/cjs/loader.js:637:17)
0|ff     |     at require (internal/modules/cjs/helpers.js:22:18)
0|ff     |     at Object.<anonymous> (/home/new-land/server.js:22:18)
0|ff     |     at Module._compile (internal/modules/cjs/loader.js:701:30)
0|ff     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
0|ff     |     at Module.load (internal/modules/cjs/loader.js:600:32)
0|ff     |     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
0|ff     |     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
PM2      | App [ff:0] exited with code [1] via signal [SIGINT]
PM2      | Script /home/new-land/server.js had too many unstable restarts (16). Stopped. "errored"
`

**Comment by doramart** [comment]
最好是把报错截图 完整点 这样看的清楚点

**Comment by rainyulei** [comment]
[https://github.com/rainyulei/image/blob/master/2019-03-12_075556.png?raw=true](url)

**Comment by rainyulei** [comment]
[[ https://github.com/rainyulei/image/blob/master/2019-03-12_075556.png?raw=true | height = 100px ]]

**Comment by rainyulei** [comment]
![2019-03-12_075556](https://user-images.githubusercontent.com/44006221/54150697-f6a3e080-449d-11e9-81b4-f4e5f41704b0.png)

**Comment by rainyulei** [comment]
就是这样  这个是在PM2的日志里面截取的，应该是settings 里面的
   63 行  system_noPower: '对不起，您无权执行该操作！',

**Comment by rainyulei** [comment]
还有 54行 email_notice_contentMsg: 'notice_contentMsg',

**Comment by doramart** [comment]
检查下依赖是否正确安装，目测是环境不太正常

**Comment by rainyulei** [comment]
我检查了一下  还是不行，我用nvm  尝试了node 8.9 和10.15.3 都不行，并且在这些版本下都重新安装过初始化过依赖，不知道是什么问题导致的，另外有个小提议，在目录文件下加一个PM2.yml  这样就不用指定很多初始化依赖了

**Comment by rainyulei** [comment]
想问一下 system_noPower  什么情况下会报这个错误

**Comment by doramart** [comment]
这个是配置的静态变量，你部署的是生产还是测试 有配置环境变量吗？

**Comment by rainyulei** [comment]
找到问题了，是因为，在setting 中有空格 而空格在git 上拉到centos 后再更改文件的时候，只要用编辑器打开文件而不是用vim 打开就会被重新编译，空格变成？ 这样最后几行其实是乱码。。。

**Comment by rainyulei** [comment]
感谢大大关注！网站弄好了请老大喝咖啡
