### ISSUE TITLE
DoraCMS2.1.1 npm run dev 错误

### ISSUE THREAD

**Issue by YWDMB** [doramart/DoraCMS#195]
环境
Windows 10
node 8.15.1
npm  6.4.1
Mongodb 3.6

npm run dev 错误日志信息

![7e967ee9b0dc275b6f705959d030401](https://user-images.githubusercontent.com/25597590/54209508-dd8c4580-4518-11e9-965e-1758668808d0.png)
![70e1a07a617ba9b7023775cf29e6908](https://user-images.githubusercontent.com/25597590/54209515-e11fcc80-4518-11e9-821b-24f86b434c73.png)

**Comment by YWDMB** [comment]
要安装 redis!

**Comment by doramart** [comment]
是的 需要开启redis
