### ISSUE TITLE
这个东西真棒

### ISSUE THREAD

**Issue by xiaoxi-note** [doramart/DoraCMS#196]
一个简单的CMS，做到这个程度，各种报错，居然还有1800个star，我也是服了。。

**Comment by doramart** [comment]
谢谢大牛关注

**Comment by doramart** [comment]
谢谢大牛关注

**Comment by loaden** [comment]
有认真读过README吗？还有伟大的GFW，也挺坑人的。

**Comment by loaden** [comment]
我用cnpm install也会出错，但翻墙后用npm install就没问题。

**Comment by loaden** [comment]
更正：cnpm install是没有问题的。
