### ISSUE TITLE
关于部署到服务器  npm run build 打包发布

### ISSUE THREAD

**Issue by YWDMB** [doramart/DoraCMS#197]
你好，首先感谢这位开发者的无私奉献，我遇到了一个问题。
搭建好环境后（redis,mongodb,node）
我本地操作如下：
1 npm install 
2 npm run build  (根目录下生成 dist 文件夹)
3 node server.js 
成功运行！

**怎样把项目发布到服务器？**
把dist文件夹里面的东西上传到服务器，怎么用node把他跑起来？
服务器里还有要装其他东西吗？要把那些东西上传到服务器才能跑起来？

**Comment by doramart** [comment]
把包括dist在内的所有文件传上去 服务器需要配置node环境变量为production,可以使用pm2启动 具体看看我博客里的文档 写的很详细了

**Comment by YWDMB** [comment]
[doracms 2.1.1 这个篇博客](https://www.html-js.cn/details/ry4-B-hkf.html)
node server.js 在开发环境可以跑起来

我希望在服务器上运行编译后的文件
1 npm install
2 npm run build  (生成dist文件夹)

![9641ae7cb969e7f974c4ae5ee0000da](https://user-images.githubusercontent.com/25597590/54684782-39298500-4b50-11e9-93a9-37444ef50d65.png)
![23e83ff69dbb331f0af91850c6abe21](https://user-images.githubusercontent.com/25597590/54684787-3c247580-4b50-11e9-93aa-ef2dfdb7b2f8.png)

3 把dist文件夹移入其他文件目录，node service-worker.js
![d5049855004e7a61babcdb1a779720d](https://user-images.githubusercontent.com/25597590/54684948-945b7780-4b50-11e9-9212-f1a238f7517b.png)

**Comment by YWDMB** [comment]
当dist文件夹与src同级目录下，
在dist目录执行 npm run start 可以跑起来，dist文件夹下部分文件被删除
![7c8e1d5927c38a88b1e307a7a327788](https://user-images.githubusercontent.com/25597590/54685402-ab4e9980-4b51-11e9-9e9a-89c3bd835e8c.png)
![b82b55e85fa79b07d16db34019ff9df](https://user-images.githubusercontent.com/25597590/54685406-adb0f380-4b51-11e9-885c-cfc1b691ad34.png)

**Comment by YWDMB** [comment]
仅有编译打包后的dist文件夹中的东西，是运行不了的吗？

**Comment by loaden** [comment]
是有源代码保密的需要，才想只提供dist给客户吧？如果是自己开发的东西，直接git在服务器上克隆，也方便后期维护啊。可以考虑贡献下代码，实现build后将dist下的内容直接发布就可以部署的功能。
