### ISSUE TITLE
2.10版本后台突然登录不上去了

### ISSUE THREAD

**Issue by wangjue666** [doramart/DoraCMS#198]
点击登录按钮 不会请求后台登录接口 一直在刷新

**Comment by wangjue666** [comment]
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://cdnjs.com/ with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
reg:25 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://cdnjs.com/ with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by wangjue666** [comment]
包括后台样式全乱掉了

**Comment by wangjue666** [comment]
解决了，之前cdn服务器跑到新域名下了，重新去他的官网找到引入才好

**Comment by loaden** [comment]
解决了请关闭下issue
