### ISSUE TITLE
关于加密解密

### ISSUE THREAD

**Issue by kylezhang** [doramart/DoraCMS#2]
对于加密key： encrypt_key : 'dora',
将‘dora’修改为其他的，生成了一个加密密码，手动加入到了db中，然后登陆的用户名和密码与db中一样，但是就是findone时，就是查不出数据，总是“登陆失败”；

您给看看，O(∩_∩)O谢谢

**Comment by doramart** [comment]
你是如何生成的加密密码，加密规则一样吗？

**Comment by kylezhang** [comment]
利用debug模式：
1：在登陆页面输入，用户名/密码： admin / admin123
2：在/routes/admin.js中 break point 到 var newPsd = DbOpt.encrypt(password,settings.encrypt_key);
3：debug到var newPsd = DbOpt.encrypt(password,settings.encrypt_key);把新生成的加密密码复制下来
以上。

**Comment by doramart** [comment]
为什么不在后台(系统用户管理)直接添加一个新用户(admin/admin123)

**Comment by kylezhang** [comment]
刚开始没有想起来O(∩_∩)O~；
是的，刚才从后台去添加了就木有问题；
3Q
