### ISSUE TITLE
关于代码目录结构的建议

### ISSUE THREAD

**Issue by xiaohn2013** [doramart/DoraCMS#20]
最近在研究你的这个cms，看到里面的目录结构稍微有点乱，
能不能前端和后端的文件分离开呀？

比如说node的单独建一个node来管理
前端的就放在public里面是否能更直观呀。

**Comment by yanghcc** [comment]
同时建议加个eslint或者prettier规范一下代码格式

**Comment by doramart** [comment]
请升级最新的DoraCMS
