### ISSUE TITLE
启动后访问报错，

### ISSUE THREAD

**Issue by gk11111** [doramart/DoraCMS#206]
启动后访问报错，Error: template not found: D:\DoraCMS-2.1.2\DoraCMS-2.1.2/views/undefined/index.html

**Comment by rya-icu** [comment]
需要先导入演示数据。做得不够完善。

**Comment by agu0991** [comment]
@liuran 演示数据在哪导入？？？

**Comment by doramart** [comment]
参考 2.1.3 根目录 readme.md
