### ISSUE TITLE
项目在本地运行好了 后台新增的文章在前端看不到

### ISSUE THREAD

**Issue by Jordonwang** [doramart/DoraCMS#207]
在后台新增的文章在前端看不到, 但是编辑以前的历史文章能生效, 直接从后台点击进文章提示参数错误,但是我在mongo数据库看了和历史的文章数据没什么差别,不知道是哪里的原因

**Comment by Jordonwang** [comment]
没有更新数据库造成的

**Comment by sullamago** [comment]
> 没有更新数据库造成的

咋解决的啊？是怎么个更新数据库方法？赐教
