### ISSUE TITLE
为什么注册会提示key must be a buffer

### ISSUE THREAD

**Issue by tbfungeek** [doramart/DoraCMS#208]
<img width="1680" alt="屏幕快照 2019-07-06 下午7 35 43 1" src="https://user-images.githubusercontent.com/7733842/60755677-72193700-a025-11e9-987e-0fd58b884492.png">

**Comment by westudiodev** [comment]
我也遇到了这个问题

**Comment by udun-cloud** [comment]
我也遇到了，研究了下代码，发现问题了

**Comment by westudiodev** [comment]
settings.js文件里加上两个参数即可：
encryptApp_key: '1234567890123456',
 encryptApp_vi: '1234567890123456',
16位随机字符

**Comment by doramart** [comment]
请使用 doracms 2.1.3
