### ISSUE TITLE
npm run start NODE_ENV 为什么是 development

### ISSUE THREAD

**Issue by netcore-jroger** [doramart/DoraCMS#211]
npm run start NODE_ENV 为什么是 development?

DoraCMS 版本：2.1.2
OS: Windows Server 2008 R2

当我改为 production 时，程序就 hang 住了。一直挂起状态。

另外问一下： MICRO_CACHE 环境变量是什么意思？

**Comment by doramart** [comment]
本地使用 npm run dev 启动开发模式，

**Comment by netcore-jroger** [comment]
其实相问的是为什么生产模式跑不起来。算了，已经用开发模式跑了。
