### ISSUE TITLE
npm run build报错

### ISSUE THREAD

**Issue by westudiodev** [doramart/DoraCMS#212]
13 verbose stack Error: doracms@2.1.2 build:client: `cross-env NODE_ENV=production webpack --config build/webpack.client.config.js --progress --hide-modules`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid doracms@2.1.2
15 verbose cwd /root/happyledger-cms
16 verbose Linux 3.10.0-957.5.1.el7.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build:client"
18 verbose node v8.16.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1

**Comment by doramart** [comment]
请使用 doracms 2.1.3
