### ISSUE TITLE
前台能否全部生成纯静态文件？

### ISSUE THREAD

**Issue by haizhilin2013** [doramart/DoraCMS#216]
想问下：
因为项目需要对SEO友好，前台能否全部生成静态文件呢？

**Comment by doramart** [comment]
DoraCMS 本身就是服务端渲染

**Comment by haizhilin2013** [comment]
> DoraCMS 本身就是服务端渲染

我是想一下子生成所有静态文件，然后把所有静态文件给客户，客户拿到的就只有静态的，没有后台node的代码
