### ISSUE TITLE
读取已审核的帖子显示无权限

### ISSUE THREAD

**Issue by Thorlph** [doramart/DoraCMS#218]
用管理员账号发布帖子后即使选择已审核，游客访问网页帖子显示无权限。
通过接口访问显示操作成功但无数据
{
    "status": 200,
    "message": "操作成功",
    "server_time": 1571906153047,
    "data": {}
}
发布的帖子在首页能显示简介和缩略图，进入详情页就显示无权限，请问怎么解决？

**Comment by doramart** [comment]
你需要在帖子编辑的时候指定用户
