### ISSUE TITLE
按照readme搭好启动之后404，请教下问题在哪里，node 环境 v10.16.3

### ISSUE THREAD

**Issue by syifeng** [doramart/DoraCMS#219]
按照readme搭好启动之后404，请教下问题在哪里，node 环境 v10.16.3，monggodb无密码，表也已经创建
![屏幕快照 2019-11-04 下午6 49 53](https://user-images.githubusercontent.com/7510994/68115766-22e00600-ff34-11e9-9338-907becba1d65.png)
<img width="590" alt="屏幕快照 2019-11-04 下午6 52 01" src="https://user-images.githubusercontent.com/7510994/68115804-368b6c80-ff34-11e9-9dee-181d22469916.png">

**Comment by doramart** [comment]
>初始化数据没有成功
