### ISSUE TITLE
大神，帮忙看下日志，什么原因

### ISSUE THREAD

**Issue by waini1110** [doramart/DoraCMS#23]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle doracms@1.1.0~prestart: doracms@1.1.0
6 silly lifecycle doracms@1.1.0~prestart: no script for prestart, continuing
7 info lifecycle doracms@1.1.0~start: doracms@1.1.0
8 verbose lifecycle doracms@1.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle doracms@1.1.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/root/DoraCMS/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle doracms@1.1.0~start: CWD: /root/DoraCMS
11 silly lifecycle doracms@1.1.0~start: Args: [ '-c', 'node ./bin/www' ]
12 silly lifecycle doracms@1.1.0~start: Returned: code: 1  signal: null
13 info lifecycle doracms@1.1.0~start: Failed to exec start script
14 verbose stack Error: doracms@1.1.0 start: `node ./bin/www`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid doracms@1.1.0
16 verbose cwd /root/DoraCMS
17 error Linux 2.6.32-042stab111.11
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.5.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error doracms@1.1.0 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the doracms@1.1.0 start script 'node ./bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the doracms package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./bin/www
23 error You can get their info via:
23 error     npm owner ls doracms
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

---

**Comment by doramart** [comment]
是不是端口问题

**Comment by waini1110** [comment]
我看了防火墙，端口并没有什么问题啊，而且我用127.0.0.1+password都可以进redis

**Comment by doramart** [comment]
你好 问题解决了么？

**Comment by waini1110** [comment]
并没有，今天我再在服务器上重试一下。
