### ISSUE TITLE
MongoError: Mod on _id not allowed

### ISSUE THREAD

**Issue by yaochangjun** [doramart/DoraCMS#24]
更新mongodb时如果数据中存在`_id`则会报错，所以需要在更新数据库之前将`_id`键删除即可

关联mongodb版本 2.4.14

{ [MongoError: Mod on _id not allowed]
  name: 'MongoError',
  message: 'Mod on _id not allowed',
  driver: true,
  ok: 1,
  n: 0,
  code: 10148,
  errmsg: 'Mod on _id not allowed',
  writeConcernError: { code: 10148, errmsg: 'Mod on _id not allowed' } }

**Comment by doramart** [comment]
我好想没报过类似错误，更新 _id 一致应该是没问题的

**Comment by doramart** [comment]
请升级最新的DoraCMS
