### ISSUE TITLE
部署到生产环节后，打开后台页面登录，后台页面显示为空白

### ISSUE THREAD

**Issue by fengyunkkx** [doramart/DoraCMS#243]
请教一下，我这里部署到生产环节后，打开后台页面、登录，后台页面显示为空白。

看日志数据库已经成功连上了，只是界面显示不出来，不清楚问题出在哪里，还望指点。

**Comment by doramart** [comment]
截图浏览器调试模式，看看有什么报错

**Comment by fengyunkkx** [comment]
![image](https://user-images.githubusercontent.com/16741175/106378133-15d2f080-63dd-11eb-9166-51b59f6adda2.png)

**Comment by itoic** [comment]
你这不是跨域了么

**Comment by doramart** [comment]
config.prd.js 最后两行配置错误，请查看文档 https://www.doracms.com
