### ISSUE TITLE
请问现在如何更改文档属性？

### ISSUE THREAD

**Issue by buctyoyo** [doramart/DoraCMS#25]
如题，想要更改文档属性，类似于添加一种文档模板 请问如何做？

**Comment by doramart** [comment]
没明白你的意思，是换一种类型的文档还是只是前端展示改变一下？

**Comment by buctyoyo** [comment]
哦，原问题的意思是   现在文档只有两种 普通文档 jquery文档 两种，是否可以添加文档

我看了下代码 发现现在在后端写死就是这两种文档~~ 添加的话 是需要自己修改源码

**Comment by doramart** [comment]
嗯是的，需要自己改下源代码，同时有必要的话还需要在content对象里加属性，但是应该改动不会很大，你可以试一下

**Comment by buctyoyo** [comment]
主要是看到你们update log中看到 1.1中将更改文档属性给去掉了~~  
建议增加这个选项，这样这个项目就不仅仅只适应于论坛类CMS了，还可以扩展到别的产品或者行业

**Comment by doramart** [comment]
主要是不同的行业属性不一样，这个属性应该如何去自定义呢，有没有demo可以参考下

**Comment by buctyoyo** [comment]
就是基本的，比如我普通企业网站的导航图，属性只有标题  图片 链接～～   内容再多也还是不同基本属性的组合吧

发自我的 iPhone

**Comment by doramart** [comment]
其实 你添加普通文档就可以满足你的要求，只是前端展示你可以改一下模板就好了

**Comment by buctyoyo** [comment]
对，只是建议，有那个选项的话，可能比较方便一点～   😁

发自我的 iPhone

**Comment by doramart** [comment]
好的，感谢你的建议，后面的版本我考虑下这个地方，谢谢！
