### ISSUE TITLE
关于title

### ISSUE THREAD

**Issue by kylezhang** [doramart/DoraCMS#3]
关于title上的小图标，您是怎么加的？我没有找到地方；
一般不都是link rel="shortcut icon" 通过这个引用么，

**Comment by doramart** [comment]
这个我没有设置，默认情况下 express 是找设置公共目录的文件夹(public)根目录下的 favicon.ico文件,当然，你也可以在app.js下设置路径 app.use(favicon(__dirname + '/public/favicon.ico'));

**Comment by kylezhang** [comment]
恩，我看到了这句，但是注释了的；
//app.use(favicon(__dirname + '/public/favicon.ico'));
我现在把public下面的那个favicon.ico换成自己对好了；
