### ISSUE TITLE
为什么我无法用node app.js来开启程序

### ISSUE THREAD

**Issue by feizeng** [doramart/DoraCMS#36]
用webstorm调试node程序的时候 默认使用node app.js开启程序的，所以会在webstorm里面调试程序的时候会报错！

**Comment by doramart** [comment]
用的是express框架，需要用npm start 启动

**Comment by feizeng** [comment]
我已经解决了， 我写了个linsten（81）监听端口，已经可以用node app.js启动程序了！

**Comment by qqfans** [comment]
Run config
JavaScript File：.\bin\www

**Comment by chinakids** [comment]
楼上正解   node ./bin/www
