### ISSUE TITLE
关于本CMS系统发送邮件失败的问题

### ISSUE THREAD

**Issue by feizeng** [doramart/DoraCMS#37]
我在文档里面看到作者写了删除邮件模块，但是在源码里面却还有发送邮件的代码，不知道是怎么回事！所以希望作者说明一下，谢谢

**Comment by doramart** [comment]
没明白你的意思 是有发送邮件模块，但是删除邮件貌似没有 加QQ群：524385285 把问题描述下

**Comment by doramart** [comment]
请升级最新的DoraCMS
