### ISSUE TITLE
强烈建议增加mysql版本

### ISSUE THREAD

**Issue by ghost** [doramart/DoraCMS#38]
毕竟mysql的维护还是比较方便的，请增加mysql版本，多谢，或者留多一个可配置的口。

**Comment by doramart** [comment]
感谢您的建议，后续的版本考虑下，谢谢！

**Comment by xujingbao** [comment]
铜球，对于大型的web管理系统，mysql需求还是更大的

**Comment by yuexing0921** [comment]
如果要增加mysql的话，我觉得可以用egg或者thinkjs来重构下，他们这方面的坑已经踩的足够多了

**Comment by doramart** [comment]
暂时不支持mysql，但是最新版本的DoraCMS 已经使用egg重构了

**Comment by doramart** [comment]
DoraCMS-SQL 版本已开源，请关注 https://gitee.com/doramart/DoraCMS-SQL

**Comment by doramart** [comment]
DoraCMS-SQL 版本已开源，请关注 https://github.com/doramart/DoraCMS-SQL

**Comment by u2bo** [comment]
> DoraCMS-SQL 版本已开源，请关注 https://github.com/doramart/DoraCMS-SQL

mysql的版本是不维护了吗？还是有什么方式可以快速迁移到mysql的版本上
