### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by cheekahao** [doramart/DoraCMS#39]
按照文档插入数据，登陆时，提示非法参数，调试后发现routes/admin.js中validator.isUserName(userName)为false。将其注释掉后，返回用户名密码错误，检查数据库，中"username" 为"test",  "password"为"581fbebb8a5f5827"，是哪里错了吗?手动叫password改为000000了无法登陆。能告诉密码在数据库中是以什么加密方式存储的吗？为什么无法登陆？

**Comment by doramart** [comment]
密码应该不能为000000这么简单，应该是字母和数字组合
