### ISSUE TITLE
关于文档管理字段--“类目”

### ISSUE THREAD

**Issue by kylezhang** [doramart/DoraCMS#4]
您好！
想问问，能不能把后台的menu文档管理中的”类目“的内容显示为对应的name，
这样做的目的是看起来更加的清晰，
就像看域名比看ip要容易些；

如：
改修前：类目 EJFzljaw
该秀后：类目 关于我

**Comment by doramart** [comment]
你好，这个地方一直没处理，有两个办法：
1、添加文档入库时带上类别的名称（目前只带了ID）
2、文档列表数据显示的时候，添加一个angular的扩展方法，通过类别ID查询后返回类别名称。

建议使用第二种方式，至少获取的数据是新的，虽然查询耗时间。第一种方式虽然简单，但是不能保证中途会更改类别名称，你可以都尝试一下，后续我做一下优化

**Comment by kylezhang** [comment]
OK，回家了也在实时关注coding，~\(≧▽≦)/~赞

**Comment by kylezhang** [comment]
那个超时时间怎么设置的？
想在dev时不要有这块超时退出？
谢谢！！！

**Comment by doramart** [comment]
你说的是后台登录么，在app.js里吧

**Comment by kylezhang** [comment]
是后台，
恩，上次看了完了，~(@^_^@)~
