### ISSUE TITLE
验证图片问题

### ISSUE THREAD

**Issue by TaijiGao** [doramart/DoraCMS#46]
![default](https://cloud.githubusercontent.com/assets/7477851/20472513/50874276-aff5-11e6-829f-1afd95494e63.png)
初始登录页面没有问题，在登录页面停留一段时间，刷新登录页面，验证图片出现undefined。此时只有关闭redis，重启redis后app才正常。
 登录进系统，在任意页面停留一段时间，再操作后会回到登录页面，此时登录页面的验证图片也同样会出现
undefined问题。
结论：session过期后，管理员登录页面的验证图片请求会有问题，且无法解决，只能通过重启redis来解决，目前还找不出问题的bug所在。测试浏览器为firefox，win10系统本机,

**Comment by doramart** [comment]
是有问题，验证码跟session有关系

**Comment by TaijiGao** [comment]
能否解决这个问题？

**Comment by doramart** [comment]
请升级到 DoraCMS 最新版本
