### ISSUE TITLE
后台为什么不是SPA的

### ISSUE THREAD

**Issue by cjz9032** [doramart/DoraCMS#49]
ejs和ng混写还是有点奇怪的样子...
是ejs有什么不可替代的地方吗

**Comment by doramart** [comment]
你用jade也是可以的，看自己的习惯

**Comment by doramart** [comment]
DoraCMS2 后台已经改为spa了，有兴趣可以关注下！

**Comment by cjz9032** [comment]
哦哦,以前毕设已经写完了~不需要了 哈哈哈
现在去公司上班也多亏这些学了,多谢!
