### ISSUE TITLE
关于函数

### ISSUE THREAD

**Issue by kylezhang** [doramart/DoraCMS#5]
1，checkIfParent：这个函数的return 是不是 有问题呀？都是return true；

**Comment by doramart** [comment]
这里用的是ztree的插件，如果没有子节点，返回的应该是false，当然需要选中节点（点击一下节点），才会有正确的判断

**Comment by kylezhang** [comment]
对了，我又看了下，确实要选中，才能成功删除掉，

**Comment by doramart** [comment]
嗯  是的
