### ISSUE TITLE
这是怎么回事

### ISSUE THREAD

**Issue by myjianyue** [doramart/DoraCMS#51]
doracms@1.1.1 start /Users/myjianyue/Desktop/projectsSpace/express/DoraCMS
> node ./bin/www

Port 81 requires elevated privileges

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! doracms@1.1.1 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the doracms@1.1.1 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the doracms package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs doracms
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls doracms
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/myjianyue/Desktop/projectsSpace/express/DoraCMS/npm-debug.log
myjianyuedeMacBook-Pro:DoraCMS myjianyue$

**Comment by doramart** [comment]
81端口无权限访问，尝试在www中修改端口号，或者用root启动

**Comment by myjianyue** [comment]
有合适的数据库吗 初学node建mongodb有点困难

**Comment by doramart** [comment]
合适的数据库是什么意思❓

**Comment by myjianyue** [comment]
刚开始学习node，求一份数据库能直接进系统的

**Comment by doramart** [comment]
我这木有测试数据
