### ISSUE TITLE
首页文档无法获取到

### ISSUE THREAD

**Issue by ccfwwm** [doramart/DoraCMS#52]
### 这是我的博客测试网页。
>>http://www.myfire.top.

**Comment by bigvaliant** [comment]
我也遇到这个问题，我是在models/db/siteFunc.js  修改函数renderToTargetPageByType  type等于index的render 为  res.render(targetPath , siteFunc.setDataForIndex(req, res, {'state' : true} , temp.alias, defaultTempPath));

**Comment by doramart** [comment]
试试把文档添加到二级分类
