### ISSUE TITLE
关于后台上传图片 

### ISSUE THREAD

**Issue by kylezhang** [doramart/DoraCMS#6]
在添加文档的时候，上传图片成功之后，上传的图片没有正确的缩略图显示出来，而是一个类似not found的默认图；请看下图。
![upload](https://cloud.githubusercontent.com/assets/3679798/10747805/9607f5f6-7c94-11e5-939c-80d2c43ad437.png)

**Comment by doramart** [comment]
本地安装GraphicsMagick Display ，否则会上传失败

**Comment by kylezhang** [comment]
哦哦，搜噶
3Q

**Comment by feizeng** [comment]
为什么我在本地安装之后GM还是会报错，找不到图片路径呢？ the gm/convert binaries can't be found

**Comment by doramart** [comment]
gm 安装正常成功吗？什么操作系统

**Comment by feizeng** [comment]
OK了 我重新装了一下GM display 在windows，希望大神的这个CMS越来越好！

**Comment by doramart** [comment]
谢谢哈，一起进步！

**Comment by SummerF** [comment]
发现一个小bug，添加广告轮播的小按钮，两张没问题，三张或以上就只会显示两个。

**Comment by hejialianghe** [comment]
2.1.3这个版本上传图片有问题，接口报错

**Comment by doramart** [comment]
请升级最新的DoraCMS
