### ISSUE TITLE
添加主分类之后前端页面报错,渲染不出来

### ISSUE THREAD

**Issue by lqigbtnnqkmm** [doramart/DoraCMS#60]
RT

**Comment by doramart** [comment]
麻烦把报错日志贴出来看下

**Comment by lqigbtnnqkmm** [comment]
![ask1](https://user-images.githubusercontent.com/26808108/30311096-4d5512e0-97c6-11e7-9b7e-3d8c95e1a84b.png)
![ask2](https://user-images.githubusercontent.com/26808108/30311098-5158adac-97c6-11e7-9136-e12050ca6384.png)
![ask3](https://user-images.githubusercontent.com/26808108/30311101-5370145e-97c6-11e7-88e1-317dae526c39.png)

**Comment by doramart** [comment]
请升级到 DoraCMS 最新版本
