### ISSUE TITLE
管理界面->文档管理->缩略图上传

### ISSUE THREAD

**Issue by rainzhou** [doramart/DoraCMS#66]
GET http://localhost:8081/__webpack_hmr net::ERR_INCOMPLETE_CHUNKED_ENCODING

POST http://localhost:8081/system/upload?type=images net::ERR_EMPTY_RESPONSE

图片上传有问题，怎么解决呢？谢谢。

**Comment by doramart** [comment]
看看终端有么有报错

**Comment by rainzhou** [comment]
以上 的信息还不够吧？

Provisional headers are shown
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryj5zXvbHAameeAsMa
Origin:http://localhost:8081
Referer:http://localhost:8081/manage
User-Agent:Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1

**Comment by doramart** [comment]
完全看不出来啊，能给点关键信息么？另外后台你是可以进去了吧？

**Comment by rainzhou** [comment]
是的，只是不能上传，可能是某些配置的问题，我基本上都是默认配置，MAC和Linux环境。有需要注意的么。

**Comment by doramart** [comment]
可能是权限问题，可以看下下面的目录是否有权限，或者debug一下
<img width="743" alt="wx20170929-150835 2x" src="https://user-images.githubusercontent.com/11911066/31004913-1af8bd6c-a4bc-11e7-91cd-ace9d48d0820.png">

**Comment by rainzhou** [comment]
谢谢，少了这2个文件夹，新建一下文件夹就好了，新问题是上传后不能显示缩略图，请问下怎么解决？

**Comment by doramart** [comment]
那你查一下上传是否成功，返回的上传路径是否正确

**Comment by rainzhou** [comment]
应该还是路径配置的问题，别的地方也有缩略图问题。在哪里修改？

**Comment by doramart** [comment]
看一下图片不显示的位置是什么路径

**Comment by rainzhou** [comment]
<img src="typeError" class="avatar"> 这样的

**Comment by rainzhou** [comment]
<img src="typeError" class="avatar">  这样的

**Comment by rainzhou** [comment]
<img src="typeError" class="avatar">

**Comment by rainzhou** [comment]
换一个图片 又成功了 不知道什么回事

**Comment by rainzhou** [comment]
![tuihuo5](https://user-images.githubusercontent.com/2169030/31006744-9c572370-a530-11e7-8f4c-961e19a1fc18.jpeg)  这个图片看不到缩略图，换了一个图片没问题。

**Comment by doramart** [comment]
你这张图片确实比较神奇，叫你一个解决办法（我也会在下个版本修复），在图中的位置加入如下代码，然后重启服务： 
`case 'ffd8ffdb':
                filetype = 'jpg';
                mimetype = ['image/jpeg', 'image/pjpeg'];
                break;
`
<img width="733" alt="wx20170929-162135 2x" src="https://user-images.githubusercontent.com/11911066/31007255-8ec86130-a4c5-11e7-9970-393bf67a1993.png">

**Comment by rainzhou** [comment]
好的 谢谢
