### ISSUE TITLE
管理界面->文档管理->文档详情上传图片

### ISSUE THREAD

**Issue by rainzhou** [doramart/DoraCMS#67]
图片上传成功，但是显示为转圈的图标，文字提示为“正在上传...”

**Comment by rainzhou** [comment]
图片上传成功，但是显示为转圈的图标，文字提示为“正在上传...”

**Comment by rainzhou** [comment]
id="loading_j86qq30o" src="/ueditor/themes/default/images/spacer.gif" title="正在上传..."

**Comment by doramart** [comment]
感觉还是跟权限有关，你试试用root权限执行npm run dev，我这边好像没这个问题

**Comment by rainzhou** [comment]
文件上传成功了，文件夹能看到文件。应该不是。

**Comment by rainzhou** [comment]
发现一个细节，上传到服务器的文件后缀是jpg，但是接口返回的后缀是jpeg。

**Comment by rainzhou** [comment]
有个新发现，多张图片上传没问题，单张图片上传就有问题。

**Comment by doramart** [comment]
请升级到 DoraCMS 最新版本
