### ISSUE TITLE
请问怎么支持多语言？

### ISSUE THREAD

**Issue by ChimingPhang** [doramart/DoraCMS#68]
我司在做公司官网，请问怎么支持多语言？

**Comment by doramart** [comment]
需要进一步开发，npm中有多语言模块可以实现你需要的功能，doracms用到的elementUI，国际化的问题可以参考这里：http://element.eleme.io/2.0/#/zh-CN/component/i18n

**Comment by ChimingPhang** [comment]
好的，谢谢，我研究下
