### ISSUE TITLE
mongodb问题

### ISSUE THREAD

**Issue by rainzhou** [doramart/DoraCMS#69]
(node:2072) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: The field 'unique' is not valid for an _id index specification. Specification: { v: 1, ns: "svideo.adminusers", key: { _id: 1 }, name: "_id_1", unique: true, background: true }

请问一下怎么破？谢谢。

**Comment by doramart** [comment]
看起来好像是你的查询条件有问题

**Comment by rainzhou** [comment]
相关代码没改

**Comment by simonwoo** [comment]
有同样的问题

**Comment by doramart** [comment]
这个问题已知晓 但不影响开发 下个版修复。

**Comment by simonwoo** [comment]
@doramart 这个问题是由于该版本的mongo不支持_id为unique照成的，把unique:true注释掉就可以了

**Comment by doramart** [comment]
是的，新版本已修复，可以checkout 最新版本
