### ISSUE TITLE
关于文档修改

### ISSUE THREAD

**Issue by kylezhang** [doramart/DoraCMS#7]
对一篇文档进行二次修改的之后，点击“提交”没有反应；

**Comment by doramart** [comment]
看看是不是有相关信息不完整，提交按钮会disable

**Comment by kylezhang** [comment]
信息是完整的，
提交按钮可以点，不是disable状态，
就是不触发
。。。。？

**Comment by doramart** [comment]
那你要看看该管理员有没有修改的权限，在用户组管理里面
