### ISSUE TITLE
如何用pm2启动 DoraCMS？

### ISSUE THREAD

**Issue by rainzhou** [doramart/DoraCMS#73]
进入源码根目录下执行：pm2 start bin/www
这个不管用，求教，谢谢。

**Comment by doramart** [comment]
pm2 start server.js

**Comment by rainzhou** [comment]
这个命令没有配置静态文件？在生产环境下。

**Comment by doramart** [comment]
没明白你的意思 这是node  启动的基本命令

**Comment by rainzhou** [comment]
在根目录下，先运行npm start build，然后运行pm2 start server.js，静态文件没有加载，是这样的么？

**Comment by doramart** [comment]
静态文件都会打包到dist目录下，你怎么看出来静态文件没加载？

**Comment by rainzhou** [comment]
网页能打开，但是样式不对

**Comment by doramart** [comment]
确认你的系统环境变量是 production

**Comment by rainzhou** [comment]
export NODE_ENV=production 先执行以上命令，已经解决，谢谢，打扰。
