### ISSUE TITLE
https配置在哪里？

### ISSUE THREAD

**Issue by mostend** [doramart/DoraCMS#74]

**Comment by doramart** [comment]
https 是要现在服务器提供商那边申请的，之后再通过ngnix 进行相应的配置

**Comment by mostend** [comment]
所以现在服务器部署只能是nginx/apache 反代到doracms？
那如果用pm2 就得自己改源码？

**Comment by doramart** [comment]
这个跟pm2 好像没有关系吧？

**Comment by yuexing0921** [comment]
https的部署和程序本身没有关系的，但是可以做一个目录，帮助下
