### ISSUE TITLE
找回密码怎么弄？

### ISSUE THREAD

**Issue by rainzhou** [doramart/DoraCMS#75]
如题，谢谢。

**Comment by doramart** [comment]
暂时没有此功能

**Comment by hongqingbox** [comment]
暂时直接修改用户数据库吧
![image](https://user-images.githubusercontent.com/16572685/34428955-0060b9be-ec8d-11e7-92c6-abc1bf4b4f2a.png)

**Comment by doramart** [comment]
请升级到 DoraCMS 最新版本
