### ISSUE TITLE
npm run start报错

### ISSUE THREAD

**Issue by 39627020** [doramart/DoraCMS#78]
我是按照下列步骤启动的。
1：npm install
2. 修改utils/settings.js到自己的日志目录和mongodb连接字符串
3.npm run build
4.npm run start

AMIDdeAir:DoraCMS amid$ npm run start

> doracms@2.0.0 start /Users/amid/work/DoraCMS
> cross-env NODE_ENV=production node ./server

server started at localhost:8080
连接数据成功
(node:85327) DeprecationWarning: `ensureIndex()` is deprecated in Mongoose >= 4.12.0, use `createIndex()` instead
(node:85327) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: The field 'unique' is not valid for an _id index specification. Specification: { v: 2, ns: "doracms2.users", key: { _id: 1 }, name: "_id_1", unique: true, background: true }
(node:85327) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:85327) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): MongoError: The field 'unique' is not valid for an _id index specification. Specification: { v: 2, ns: "doracms2.contentcategories", key: { _id: 1 }, name: "_id_1", unique: true, background: true }
(node:85327) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): MongoError: The field 'unique' is not valid for an _id index specification. Specification: { v: 2, ns: "doracms2.notifies", key: { _id: 1 }, name: "_id_1", unique: true, background: true }
(node:85327) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): MongoError: The field 'unique' is not valid for an _id index specification. Specification: { v: 2, ns: "doracms2.adsitems", key: { _id: 1 }, name: "_id_1", unique: true, background: true }
(node:85327) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): MongoError: The field 'unique' is not valid for an _id index specification. Specification: { v: 2, ns: "doracms2.admingroups", key: { _id: 1 }, name: "_id_1", unique: true, background: true }
(node:85327) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): MongoError: The field 'unique' is not valid for an _id index specification. Specification: { v: 2, ns: "doracms2.messages", key: { _id: 1 }, name: "_id_1", unique: true, background: true }
(node:85327) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): MongoError: The field 'unique' is not valid for an _id index specification. Specification: { v: 2, ns: "doracms2.systemconfigs", key: { _id: 1 }, name: "_id_1", unique: true, background: true }
(node:85327) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): MongoError: The field 'unique' is not valid for an _id index specification. Specification: { v: 2, ns: "doracms2.usernotifies", key: { _id: 1 }, name: "_id_1", unique: true, background: true }
(node:85327) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): MongoError: The field 'unique' is not valid for an _id index specification. Specification: { v: 2, ns: "doracms2.ads", key: { _id: 1 }, name: "_id_1", unique: true, background: true }
(node:85327) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): MongoError: The field 'unique' is not valid for an _id index specification. Specification: { v: 2, ns: "doracms2.adminusers", key: { _id: 1 }, name: "_id_1", unique: true, background: true }
(node:85327) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 11): MongoError: The field 'unique' is not valid for an _id index specification. Specification: { v: 2, ns: "doracms2.contents", key: { _id: 1 }, name: "_id_1", unique: true, background: true }
(node:85327) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): MongoError: The field 'unique' is not valid for an _id index specification. Specification: { v: 2, ns: "doracms2.dataoptionlogs", key: { _id: 1 }, name: "_id_1", unique: true, background: true }
(node:85327) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 13): MongoError: The field 'unique' is not valid for an _id index specification. Specification: { v: 2, ns: "doracms2.adminresources", key: { _id: 1 }, name: "_id_1", unique: true, background: true }
(node:85327) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 14): MongoError: The field 'unique' is not valid for an _id index specification. Specification: { v: 2, ns: "doracms2.contenttags", key: { _id: 1 }, name: "_id_1", unique: true, background: true }
(node:85327) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): MongoError: The field 'unique' is not valid for an _id index specification. Specification: { v: 2, ns: "doracms2.systemoptionlogs", key: { _id: 1 }, name: "_id_1", unique: true, background: true }
"GET /api/systemConfig/getConfig?cache=true" 200 29 "-" "axios/0.16.2"
"GET /api/contentCategory/getList?model=full&path=%2F&cache=true" 200 85 "-" "axios/0.16.2"
"GET /api/content/getSimpleListByParams?pageSize=10&sortby=clickNum&model=simple&cache=true" 200 83 "-" "axios/0.16.2"
"GET /api/contentTag/getList?pageSize=30&cache=true" 200 83 "-" "axios/0.16.2"
"GET /api/content/getList?model=normal&pageSize=10&path=%2F&cache=true" 200 83 "-" "axios/0.16.2"
data pre-fetch: 391ms
error during render : /
TypeError: Cannot read property 'siteName' of undefined
    at VueComponent.metaInfo [as $metaInfo] (server/server-bundle.js:3694:34)
    at VueComponent.created (/Users/amid/work/DoraCMS/node_modules/vue-meta/lib/vue-meta.js:1030:15)
    at callHook (/Users/amid/work/DoraCMS/node_modules/vue/dist/vue.runtime.common.js:2815:21)
    at VueComponent.Vue._init (/Users/amid/work/DoraCMS/node_modules/vue/dist/vue.runtime.common.js:4474:5)
    at new VueComponent (/Users/amid/work/DoraCMS/node_modules/vue/dist/vue.runtime.common.js:4644:12)
    at createComponentInstanceForVnode (/Users/amid/work/DoraCMS/node_modules/vue-server-renderer/build.js:7357:10)
    at renderComponentInner (/Users/amid/work/DoraCMS/node_modules/vue-server-renderer/build.js:7542:40)
    at renderComponent (/Users/amid/work/DoraCMS/node_modules/vue-server-renderer/build.js:7517:5)
    at renderNode (/Users/amid/work/DoraCMS/node_modules/vue-server-renderer/build.js:7433:5)
    at renderComponentInner (/Users/amid/work/DoraCMS/node_modules/vue-server-renderer/build.js:7553:3)
    at renderComponent (/Users/amid/work/DoraCMS/node_modules/vue-server-renderer/build.js:7517:5)
    at renderNode (/Users/amid/work/DoraCMS/node_modules/vue-server-renderer/build.js:7433:5)
    at renderComponentInner (/Users/amid/work/DoraCMS/node_modules/vue-server-renderer/build.js:7553:3)
    at renderComponent (/Users/amid/work/DoraCMS/node_modules/vue-server-renderer/build.js:7517:5)
    at RenderContext.renderNode (/Users/amid/work/DoraCMS/node_modules/vue-server-renderer/build.js:7433:5)
    at RenderContext.next (/Users/amid/work/DoraCMS/node_modules/vue-server-renderer/build.js:2391:14)
"GET /" 500 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"

**Comment by doramart** [comment]
你没有导入基础数据吧？
https://www.html-js.cn/details/ryn2kSWqZ.html
![image](https://user-images.githubusercontent.com/11911066/31762484-f55f7616-b480-11e7-827f-eee8f543de31.png)

**Comment by 39627020** [comment]
谢谢及时回答，待我研究下代码，如果有用一定请大神喝咖啡。
