### ISSUE TITLE
关于 文章 打开失败

### ISSUE THREAD

**Issue by kylezhang** [doramart/DoraCMS#8]
基于模板“aboutme”成功添加了文档；
但是在前台点击了aboutme对应的链接之后出现了error，如下图过程（我也有时间传图不成功，那就把页面log发上来吧）；

程序出错了.
Failed to lookup view "web/temp/undefined/contentList" in views directory "/home/zhangkai/mycode/ABC/cms/views"
我们正在加紧处理，请稍后访问...

**Comment by doramart** [comment]
这个问题应该是你添加类别的时候没有选择ahoutMe的目标，所以找不到

**Comment by kylezhang** [comment]
是选择了的

**Comment by doramart** [comment]
你看下文档模板添加的是不是正确

**Comment by doramart** [comment]
请升级最新的DoraCMS
