### ISSUE TITLE
About log4j

### ISSUE THREAD

**Issue by dolare** [doramart/DoraCMS#80]
Hi friend,

Do you have plan to update the log4j version to 2.+?

I found the configuration rule changed a lot.

**Comment by dolare** [comment]
By the way, I'd like to help you migrate log4j from 0.* to 2.*, if you don't mind.

**Comment by doramart** [comment]
Sure, if you have tested, you can merge to ..., thank you ! (sorry, my english is poor ^_^)

**Comment by doramart** [comment]
had add to version 2.0.2
