### ISSUE TITLE
后台新用户注册和近期评论部分格式错乱

### ISSUE THREAD

**Issue by jiangwalle** [doramart/DoraCMS#82]
这两个部分要去加载upload目录里的defaultlogo.png，图片不在代码仓库里，所以，此处无法显示图片，转而现在了图片的alt信息，从而导致格式错位

**Comment by doramart** [comment]
已添加，更新一下，谢谢！

**Comment by jiangwalle** [comment]
感谢，测试确认问题已修复。可以关闭这个issue了。

**Comment by jiangwalle** [comment]
测试确认问题已修复
