### ISSUE TITLE
页面刷新后的阅读次数统计不对

### ISSUE THREAD

**Issue by jiangwalle** [doramart/DoraCMS#83]
页面阅读次数每次刷新应该加1，而不是2.

问题重现：
1.  进入博客页面, e.g. https://www.html-js.cn/details/ryn2kSWqZ.html
2. 刷新页面
3. 页面阅读次数加2

**Comment by doramart** [comment]
确有此问题，下个版本修复，谢谢！

**Comment by doramart** [comment]
问题已在v2.0.3中修复
