### ISSUE TITLE
branch2.0.2导航菜单和分类目录不显示

### ISSUE THREAD

**Issue by jiangwalle** [doramart/DoraCMS#84]
<img width="1433" alt="wx20171116-114144 2x" src="https://user-images.githubusercontent.com/8231736/32864234-31737406-cac3-11e7-835e-a399561c2a16.png">

**Comment by doramart** [comment]
缓存问题，清理下缓存，重启服务就好了

**Comment by jiangwalle** [comment]
我理解的缓存，后台的缓存是在内存中的，重启服务肯定就清除了。至于浏览器浏览器缓存，清除后，导航还是没出来。我试过切换回2.0.0branch，导航就OK了。但是搜索框会消失。

**Comment by jiangwalle** [comment]
更正一下，导航显示不出来是从2.0.1branch开始的。测试过2.0.0，导航条显示OK。
<img width="1429" alt="wx20171116-141724 2x" src="https://user-images.githubusercontent.com/8231736/32868925-36270060-cad9-11e7-8ce3-0304a362e1f6.png">

**Comment by doramart** [comment]
问题在新版本已处理！~
