### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by epubreader** [doramart/DoraCMS#9]
Doracms还不错， 呵呵， 我有几点建议。
1. 能不能对URL 进行SEO 优化。 就像keystonejs 一样， http://demo.keystonejs.com/blog/post/dasasd
1. 能不能让用户可以发表文章， 然后管理员审核文章。
2. 注册时能开启验证码就更换了。

**Comment by doramart** [comment]
你好，感谢您的认可和建议。url的seo优化你说的是针对文档详情的url吗（关键字组合的url），这个我后面考虑下。用户发文章的功能之前有考虑过，但是没有做上去，其实是可以拓展的，由于DoraCMS定位是内容管理，而不是论坛，所以没有做过多的拓展，你可以在此基础上稍加改造就可以发文章。注册的验证码问题，这个也很简单，加个表单，请求接口就可以获取验证码图片了，你可以尝试一下，感谢您的支持 ^_^~~
