### ISSUE TITLE
添加文档类别：描述信息不是必填项，但是也验证了

### ISSUE THREAD

**Issue by Keystion** [doramart/DoraCMS#91]
**DoraCMS 2.0.2**

![image](https://user-images.githubusercontent.com/2408287/33119747-e3eb4b86-cfaa-11e7-8b3c-2217590069ac.png)

添加文档类别：描述信息不是必填项，但是也验证了；
这时虽然出现了错误提示，但是文档类别添加成功，关闭错误添加文档类别弹框，刷新页面刚刚添加的新类别就会出现在页面上。

问题出在这个文件`server/lib/controller/contentCategory.js`的 checkFormData 方法内：

```
function checkFormData(req, res, fields) {
    let errMsg = '';
    ......
    if (!validator.isLength(fields.comments, 4, 100)) {  
        errMsg = '4-100个非特殊字符!';
    }
    ......
}
```

这段代码的`if (!validator.isLength(fields.comments, 4, 100)) { `处，需要增加一个判断验证用户是否输入了描述信息。

---

随之带来的一个问题；这里的描述信息验证提示是：4-100个非特殊字符!。但是在文件`src/manage/components/contentCategory/categoryForm.vue`里的验证信息提示却是：请输入5-50个字符，这两个信息需要统一下。

```
comments: [
    {
        message: "请填写备注",
        trigger: "blur"
    },
    {
        min: 4,
        max: 100,
        message: "请输入5-50个字符",
        trigger: "blur"
    }
]
```

**Comment by doramart** [comment]
已在v2.0.3版本中修复
