### ISSUE TITLE
目前发现的一些问题，在这里罗列

### ISSUE THREAD

**Issue by de1ck** [doramart/DoraCMS#93]
1. password在update表单验证方案
 最好的方式是 ： add 开启验证     update  在password输入新的密码后才开启验证
2. 系统配置中邮箱密码是直接加密过后的 导致字段长度过长问题 
3. 留言功能   (close)
管理员在留言管理中 对某个会员 回复信息， 然后再给自己（doramart）回复信息后，进入系统主页
浏览器报错：
[Vue warn]: Error in render: "TypeError: Cannot read property 'userName' of undefined"

**Comment by doramart** [comment]
密码问题目前没有找到更合适的办法，在修改资料的同时填写密码也可以接受，暂时保留。第三个问题在 v2.0.3版本中已修复

**Comment by doramart** [comment]
请升级最新的DoraCMS
