### ISSUE TITLE
404

### ISSUE THREAD

**Issue by xyclr** [doramart/DoraCMS#96]
http://127.0.0.1:8080/manage#/addContent
branch 2.03
mac os sierra    chrome

**Comment by doramart** [comment]
请设置当前用户为超级管理员权限

**Comment by hongqingbox** [comment]
建议权限没有连新增按钮都隐藏
![image](https://user-images.githubusercontent.com/16572685/34428898-59ac0740-ec8c-11e7-9ca9-204369329456.png)

**Comment by doramart** [comment]
请升级到 DoraCMS 最新版本
