### ISSUE TITLE
请问一下登录超时的时间在哪设置？

### ISSUE THREAD

**Issue by iyaq** [doramart/DoraCMS#98]
发表以前文章，编辑状态停留久的话，点击保存，直接提示登录超时。这样编辑的东西就没有了。我想修改一下这个时间，没找到~~~  谢谢

**Comment by doramart** [comment]
看图，下个版本做成可配置
![image](https://user-images.githubusercontent.com/11911066/34249190-d342d058-e673-11e7-9004-7fad8caf1002.png)

**Comment by iyaq** [comment]
谢谢大神

**Comment by Hbuilderx** [comment]
请问验证码看不到是什么问题？前台的样式也是乱的，后台验证码看不到
